Data Source for Organizations
GK-Consulting/terraform-provider-astronomer pull request #8
Opened 2023-12-28 21:03 UTC by ikegentz

2023-12-28 21:50 UTC, OpenGLShaders commented on internal/api/org.go
> +	IsScumEnabled  bool                `json:"isScimEnabled"`
scum->scim

2023-12-28 23:08 UTC, ikegentz commented on internal/api/org.go
> +	IsScumEnabled  bool                `json:"isScimEnabled"`
TY, fixed

2023-12-29 04:20 UTC, OpenGLShaders requested changes

2023-12-29 04:20 UTC, OpenGLShaders commented on internal/api/org.go
> +type BasicSubjectProfile struct {
I suggest postfixing with `Response` to make it clear that this is from the API. I have tried to do this in my api clients but I need to update a few, which I will open a PR for.

2023-12-29 04:20 UTC, OpenGLShaders commented on internal/provider/org_data_source.go
> +	Status         types.String         `tfsdk:"status"`
I would leave status out - as it's something that can be transiently different than the state. Same thing in the domain model. 

Basically this could cause a diff in your plan but there's no way to change or update it

2023-12-29 04:20 UTC, OpenGLShaders commented on internal/provider/org_data_source.go
> +	ID             types.String         `tfsdk:"id"`
nit: convention is to use `Id`

2023-12-29 04:20 UTC, OpenGLShaders commented on internal/provider/org_data_source.go
> +		// This description is used by the documentation generator and the language server.
you'll want to create an example file in the examples directory and run `go generate`

2023-12-29 04:20 UTC, OpenGLShaders commented on internal/provider/org_data_source_test.go
> +`, orgId, workspaceName)
this workspaceName arg isn't used

2023-12-29 16:11 UTC, ikegentz commented on internal/api/org.go
> +type BasicSubjectProfile struct {
Good thought - updated

2023-12-29 16:13 UTC, ikegentz commented on internal/provider/org_data_source.go
> +	Status         types.String         `tfsdk:"status"`
This one is pretty limited in what it will return:

![image](https://github.com/GK-Consulting/terraform-provider-astronomer/assets/31357832/5bd0b0aa-d1c3-455f-ab68-f3678af254bd)

Also I think it's generally best to return as much data as possible as the end user can always disable a diff with `ignore_changes`, especially where this is a `data_source` instead of a `resource`.

2023-12-29 16:15 UTC, ikegentz commented on internal/provider/org_data_source.go
> +	ID             types.String         `tfsdk:"id"`
fixed

2023-12-29 16:19 UTC, ikegentz commented on internal/provider/org_data_source.go
> +		// This description is used by the documentation generator and the language server.
Nice - added

2023-12-29 16:21 UTC, ikegentz commented on internal/provider/org_data_source_test.go
> +`, orgId, workspaceName)
Whoops - copypasta error.

2023-12-29 16:22 UTC, ikegentz commented
@OpenGLShaders TY for the review. Addressed all comments but left one open for discussion w.r.t. if "status" should be included

2023-12-29 17:13 UTC, OpenGLShaders commented on internal/provider/org_data_source.go
> +	Status         types.String         `tfsdk:"status"`
I see - this wouldn't be changing rapidly, so I think this is perfect. I agree more info is often preferable but when it comes to health statuses - even AWS resources don't return that

2023-12-29 17:13 UTC, OpenGLShaders approved these changes

2023-12-29 17:21 UTC, merged